site_name: Jonas
site_url: https://jonas.io
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline 
        name: dark mode
    - scheme: slate 
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs


